export const ALGERIA_ADMIN_META = {
  "official_wilaya_count": 69,
  "official_commune_count": 1541,
  "legal_basis": "Law 26-06 of 4 April 2026, Official Journal No. 25 of 5 April 2026",
  "transition_end": "2026-12-31",
  "full_autonomy": "2027-01-01",
  "official_source": "https://www.joradp.dz/FTP/jo-francais/2026/F2026025.pdf",
  "ministry_source": "https://interieur.gov.dz/2025/12/18/le-ministre-de-linterieur-des-collectivites-locales-et-des-transports-presente-le-projet-de-loi-relatif-a-lorganisation-territoriale-du-pays-devant-la-commission-competente-du-conse/",
  "boundary_source": "OpenStreetMap admin_level=4 via GeoAlgeria; 69-feature 2026 boundary dataset",
  "boundary_license": "ODbL-1.0",
  "boundary_attribution": "© OpenStreetMap contributors"
};

export const WILAYA_DATA = {
  "Adrar": {
    "code": 1,
    "name_ar": "أدرار",
    "name_fr": "Adrar",
    "capital": "Adrar",
    "region": "South",
    "created": 1984,
    "communes_count": 16,
    "dairas_count": 6,
    "mother_wilaya": null,
    "official_source": "https://www.joradp.dz/FTP/jo-francais/2026/F2026025.pdf",
    "fact": "The second largest province, renowned for its ancient foggaras (traditional irrigation), clay Ksours, and historic manuscripts.",
    "fact_fr": "La deuxième plus grande province, réputée pour ses anciens foggaras (irrigation traditionnelle), ses ksour en argile et ses manuscrits historiques.",
    "fact_ar": "ثاني أكبر ولاية في الجزائر، تتميز بنظام ري الفوقارات التقليدي وقصورها الطينية التاريخية ومخطوطاتها القديمة.",
    "fact_status": "legacy-local-fact"
  },
  "Chlef": {
    "code": 2,
    "name_ar": "الشلف",
    "name_fr": "Chlef",
    "capital": "Chlef",
    "region": "North",
    "created": 1984,
    "communes_count": 35,
    "dairas_count": 13,
    "mother_wilaya": null,
    "official_source": "https://www.joradp.dz/FTP/jo-francais/2026/F2026025.pdf",
    "fact": "Founded as the Roman city Castellum Tingitanum, situated in the fertile Chelif basin between the Mediterranean and the Ouarsenis mountains.",
    "fact_fr": "Fondée sous le nom romain de Castellum Tingitanum, située dans le bassin fertile du Chelif, entre la Méditerranée et les montagnes de l'Ouarsenis.",
    "fact_ar": "تأسست كمدينة رومانية (كاستيلوم تينجيتانوم)، وتقع في حوض الشلف الزراعي الخصب الذي يحده البحر المتوسط وجبال الونشريس.",
    "fact_status": "legacy-local-fact"
  },
  "Laghouat": {
    "code": 3,
    "name_ar": "الأغواط",
    "name_fr": "Laghouat",
    "capital": "Laghouat",
    "region": "Central",
    "created": 1984,
    "communes_count": 12,
    "dairas_count": 5,
    "mother_wilaya": null,
    "official_source": "https://www.joradp.dz/FTP/jo-francais/2026/F2026025.pdf",
    "fact": "Known as the capital of the Steppes and Gateway to the Sahara, famous for its magical palm groves and historical Saharan trade routes.",
    "fact_fr": "Connue comme la capitale des steppes et la porte du Sahara, célèbre pour ses palmeraies magiques et les routes commerciales sahariennes.",
    "fact_ar": "عاصمة السهوب وبوابة الصحراء، تتميز ببساتين النخيل الساحرة وممراً تاريخياً للقوافل التجارية العابرة للصحراء.",
    "fact_status": "legacy-local-fact"
  },
  "Oum El Bouaghi": {
    "code": 4,
    "name_ar": "أم البواقي",
    "name_fr": "Oum El Bouaghi",
    "capital": "Oum El Bouaghi",
    "region": "East",
    "created": 1984,
    "communes_count": 29,
    "dairas_count": 12,
    "mother_wilaya": null,
    "official_source": "https://www.joradp.dz/FTP/jo-francais/2026/F2026025.pdf",
    "fact": "Located in the heart of the Aurès, rich in Roman archaeological sites (like Sigus) and characterized by vast agricultural and pastoral lands.",
    "fact_fr": "Située au cœur des Aurès, riche en sites archéologiques romains (comme Sigus) et caractérisée par de vastes terres agricoles et pastorales.",
    "fact_ar": "تقع في قلب الأوراس، وتزخر بمواقع أثرية رومانية (مثل سيقوس) وتتميز بطابعها الفلاحي والرعوي الممتد.",
    "fact_status": "legacy-local-fact"
  },
  "Batna": {
    "code": 5,
    "name_ar": "باتنة",
    "name_fr": "Batna",
    "capital": "Batna",
    "region": "East",
    "created": 1984,
    "communes_count": 53,
    "dairas_count": 18,
    "mother_wilaya": null,
    "official_source": "https://www.joradp.dz/FTP/jo-francais/2026/F2026025.pdf",
    "fact": "Capital of the majestic Aurès, home to the magnificent Roman ruins of Timgad, the stunning Ghoufi canyons, and beautiful mountain nature.",
    "fact_fr": "Capitale des majestueuses Aurès, abritant les magnifiques ruines romaines de Timgad, les superbes canyons de Ghoufi et une belle nature montagneuse.",
    "fact_ar": "عاصمة الأوراس الشامخة، تضم جوهرة الآثار الرومانية تيمقاد وشرفات الغوفي الجيولوجية المذهلة وطبيعة جبلية ساحرة.",
    "fact_status": "legacy-local-fact"
  },
  "Béjaïa": {
    "code": 6,
    "name_ar": "بجاية",
    "name_fr": "Béjaïa",
    "capital": "Béjaïa",
    "region": "North",
    "created": 1984,
    "communes_count": 52,
    "dairas_count": 19,
    "mother_wilaya": null,
    "official_source": "https://www.joradp.dz/FTP/jo-francais/2026/F2026025.pdf",
    "fact": "Historical capital of the Hammadid dynasty, a stunning coastal city featuring the Yemma Gouraya peak, Cap Carbon, and a strategic port.",
    "fact_fr": "Capitale historique de la dynastie hammadide, une magnifique ville côtière avec le pic de Yemma Gouraya, le Cap Carbon et un port stratégique.",
    "fact_ar": "عاصمة الحماديين تاريخياً، مدينة ساحلية خلابة تجمع بين قمة يما قورايا، رأس كربون، وميناء استراتيجي هام.",
    "fact_status": "legacy-local-fact"
  },
  "Biskra": {
    "code": 7,
    "name_ar": "بسكرة",
    "name_fr": "Biskra",
    "capital": "Biskra",
    "region": "East",
    "created": 1984,
    "communes_count": 22,
    "dairas_count": 7,
    "mother_wilaya": null,
    "official_source": "https://www.joradp.dz/FTP/jo-francais/2026/F2026025.pdf",
    "fact": "The Queen of the Zibans and capital of Dates (Deglet Nour), a vital transit hub between north and south with renowned thermal springs.",
    "fact_fr": "La Reine des Zibans et capitale des Dattes (Deglet Nour), un carrefour de transit vital entre le nord et le sud avec des sources thermales renommées.",
    "fact_ar": "عروس الزيبان وعاصمة التمور (دقلة نور)، تعتبر نقطة عبور حيوية بين الشمال والجنوب وتشتهر بينابيعها المعدنية.",
    "fact_status": "legacy-local-fact"
  },
  "Béchar": {
    "code": 8,
    "name_ar": "بشار",
    "name_fr": "Béchar",
    "capital": "Béchar",
    "region": "South",
    "created": 1984,
    "communes_count": 11,
    "dairas_count": 6,
    "mother_wilaya": null,
    "official_source": "https://www.joradp.dz/FTP/jo-francais/2026/F2026025.pdf",
    "fact": "An economic and mining hub in the southwest, home to the breathtaking Taghit oases, Mount Antar, and rich Gnawa heritage.",
    "fact_fr": "Un pôle économique et minier dans le sud-ouest, abritant les oasis à couper le souffle de Taghit, le mont Antar et un riche patrimoine Gnawa.",
    "fact_ar": "قطب اقتصادي ومنجمي في الجنوب الغربي، تضم واحات تاغيت الخلابة وجبال عنتر، وتتميز بتراث غناوي أصيل.",
    "fact_status": "legacy-local-fact"
  },
  "Blida": {
    "code": 9,
    "name_ar": "البليدة",
    "name_fr": "Blida",
    "capital": "Blida",
    "region": "North",
    "created": 1984,
    "communes_count": 25,
    "dairas_count": 10,
    "mother_wilaya": null,
    "official_source": "https://www.joradp.dz/FTP/jo-francais/2026/F2026025.pdf",
    "fact": "The City of Roses, nestled at the foot of the Blidean Atlas, home to Chréa National Park known for its cedar forests and winter skiing.",
    "fact_fr": "La Ville des Roses, nichée au pied de l'Atlas blidéen, abritant le parc national de Chréa, connu pour ses forêts de cèdres et le ski en hiver.",
    "fact_ar": "مدينة الورود، تتربع عند سفح الأطلس البليدي، وتضم الحظيرة الوطنية للشريعة التي تتميز بغابات الأرز والتزلج شتاءً.",
    "fact_status": "legacy-local-fact"
  },
  "Bouira": {
    "code": 10,
    "name_ar": "البويرة",
    "name_fr": "Bouira",
    "capital": "Bouira",
    "region": "North",
    "created": 1984,
    "communes_count": 45,
    "dairas_count": 12,
    "mother_wilaya": null,
    "official_source": "https://www.joradp.dz/FTP/jo-francais/2026/F2026025.pdf",
    "fact": "A strategic region with fertile plains, guarded by the Djurdjura mountains containing the beautiful Tikjda ski and nature resort.",
    "fact_fr": "Une région stratégique avec des plaines fertiles, gardée par les montagnes du Djurdjura contenant la magnifique station de ski et de nature de Tikjda.",
    "fact_ar": "منطقة استراتيجية وتاريخية، تتوسطها السهول الخصبة وتحرسها جبال جرجرة حيث تقع المحطة المناخية والسياحية تيكجدة.",
    "fact_status": "legacy-local-fact"
  },
  "Tamanrasset": {
    "code": 11,
    "name_ar": "تمنراست",
    "name_fr": "Tamanrasset",
    "capital": "Tamanrasset",
    "region": "South",
    "created": 1984,
    "communes_count": 5,
    "dairas_count": 3,
    "mother_wilaya": null,
    "official_source": "https://www.joradp.dz/FTP/jo-francais/2026/F2026025.pdf",
    "fact": "The largest province and capital of the Tuareg, harboring the volcanic Ahaggar Mountains and Mount Tahat, Algeria's highest peak.",
    "fact_fr": "La plus grande province et capitale des Touaregs, abritant le massif volcanique du Hoggar et le mont Tahat, le point culminant de l'Algérie.",
    "fact_ar": "أكبر ولايات الجزائر وعاصمة الطوارق، تحتضن سلسلة جبال الهقار البركانية وقمة تاهات (أعلى قمة في البلاد).",
    "fact_status": "legacy-local-fact"
  },
  "Tébessa": {
    "code": 12,
    "name_ar": "تبسة",
    "name_fr": "Tébessa",
    "capital": "Tébessa",
    "region": "East",
    "created": 1984,
    "communes_count": 24,
    "dairas_count": 10,
    "mother_wilaya": null,
    "official_source": "https://www.joradp.dz/FTP/jo-francais/2026/F2026025.pdf",
    "fact": "The ancient Roman city of Theveste, containing world-class monuments like the Byzantine Wall, Arch of Caracalla, and rich green nature.",
    "fact_fr": "L'ancienne ville romaine de Theveste, abritant des monuments de classe mondiale comme la muraille byzantine, l'arc de Caracalla et une riche nature verdoyante.",
    "fact_ar": "مدينة ثييفست الرومانية القديمة، تضم معالم أثرية عالمية كالسور البيزنطي وقوس كاراكالا وطبيعة خضراء غنية.",
    "fact_status": "legacy-local-fact"
  },
  "Tlemcen": {
    "code": 13,
    "name_ar": "تلمسان",
    "name_fr": "Tlemcen",
    "capital": "Tlemcen",
    "region": "West",
    "created": 1984,
    "communes_count": 49,
    "dairas_count": 19,
    "mother_wilaya": null,
    "official_source": "https://www.joradp.dz/FTP/jo-francais/2026/F2026025.pdf",
    "fact": "Pearl of the Central Maghreb and Zayyanid capital, a city of Islamic and Andalusian art, home to Beni Add caves and L'Ourit waterfalls.",
    "fact_fr": "Perle du Maghreb central et capitale zianide, ville d'art islamique et andalou, abritant les grottes de Beni Add et les cascades de L'Ourit.",
    "fact_ar": "لؤلؤة المغرب الأوسط وعاصمة الزيانيين، مدينة الفن والتاريخ الإسلامي والأندلسي، تضم مغارات بني عاد وشلالات لوريط.",
    "fact_status": "legacy-local-fact"
  },
  "Tiaret": {
    "code": 14,
    "name_ar": "تيارت",
    "name_fr": "Tiaret",
    "capital": "Tiaret",
    "region": "West",
    "created": 1984,
    "communes_count": 36,
    "dairas_count": 12,
    "mother_wilaya": null,
    "official_source": "https://www.joradp.dz/FTP/jo-francais/2026/F2026025.pdf",
    "fact": "Capital of the Rustamid dynasty (Tahert), a fertile steppe region world-renowned for equestrianism and breeding pure Arabian horses.",
    "fact_fr": "Capitale de la dynastie rostémide (Tahert), une région de steppe fertile mondialement réputée pour l'équitation et l'élevage de chevaux pur-sang arabes.",
    "fact_ar": "عاصمة الرستميين (تاهرت)، منطقة سهوب خصبة تشتهر عالمياً بالفروسية وتربية الخيول العربية الأصيلة.",
    "fact_status": "legacy-local-fact"
  },
  "Tizi Ouzou": {
    "code": 15,
    "name_ar": "تيزي وزو",
    "name_fr": "Tizi Ouzou",
    "capital": "Tizi Ouzou",
    "region": "North",
    "created": 1984,
    "communes_count": 67,
    "dairas_count": 21,
    "mother_wilaya": null,
    "official_source": "https://www.joradp.dz/FTP/jo-francais/2026/F2026025.pdf",
    "fact": "The heart of Kabylia, known for its imposing Djurdjura mountains, famous for breathtaking nature, traditional crafts, and olive oil.",
    "fact_fr": "Le cœur de la Kabylie, connu pour ses imposantes montagnes du Djurdjura, célèbre pour sa nature à couper le souffle, son artisanat traditionnel et son huile d'olive.",
    "fact_ar": "قلب منطقة القبائل، جبالها الشامخة كجرجرة وتشتهر بالطبيعة الخلابة والصناعات التقليدية وزيت الزيتون الممتاز.",
    "fact_status": "legacy-local-fact"
  },
  "Algiers": {
    "code": 16,
    "name_ar": "الجزائر",
    "name_fr": "Alger",
    "capital": "Algiers",
    "region": "North",
    "created": 1984,
    "communes_count": 57,
    "dairas_count": 13,
    "mother_wilaya": null,
    "official_source": "https://www.joradp.dz/FTP/jo-francais/2026/F2026025.pdf",
    "fact": "Algiers the Well-Guarded, the capital city, renowned for its historic Casbah (World Heritage site), stunning bay, and rich maritime history.",
    "fact_fr": "Alger la Bien-Gardée, la capitale, célèbre pour sa Casbah historique (patrimoine mondial), sa baie magnifique et sa riche histoire maritime.",
    "fact_ar": "الجزائر المحروسة، عاصمة البلاد، تتميز بقصباتها التاريخية (تراث عالمي) وخليجها الساحر وتاريخها البحري العريق.",
    "fact_status": "legacy-local-fact"
  },
  "Djelfa": {
    "code": 17,
    "name_ar": "الجلفة",
    "name_fr": "Djelfa",
    "capital": "Djelfa",
    "region": "Central",
    "created": 1984,
    "communes_count": 18,
    "dairas_count": 6,
    "mother_wilaya": null,
    "official_source": "https://www.joradp.dz/FTP/jo-francais/2026/F2026025.pdf",
    "fact": "The largest livestock market, capital of Ouled Naïl, rich in prehistoric rock engravings and centrally located in the High Steppes.",
    "fact_fr": "Le plus grand marché aux bestiaux, capitale des Ouled Naïl, riche en gravures rupestres préhistoriques et située au centre des Hauts Plateaux.",
    "fact_ar": "أكبر سوق للمواشي، عاصمة أولاد نايل، تزخر بالنقوش الصخرية التي تعود لعصور ما قبل التاريخ وتتوسط السهوب العليا.",
    "fact_status": "legacy-local-fact"
  },
  "Jijel": {
    "code": 18,
    "name_ar": "جيجل",
    "name_fr": "Jijel",
    "capital": "Jijel",
    "region": "North",
    "created": 1984,
    "communes_count": 28,
    "dairas_count": 11,
    "mother_wilaya": null,
    "official_source": "https://www.joradp.dz/FTP/jo-francais/2026/F2026025.pdf",
    "fact": "Pearl of the coast, historically a naval base for the Barbarossa brothers, featuring dense coastal forests and the Marvelous Caves.",
    "fact_fr": "Perle de la côte, historiquement base navale des frères Barberousse, caractérisée par des forêts côtières denses et les Grottes Merveilleuses.",
    "fact_ar": "لؤلؤة الساحل، اشتهرت كقاعدة بحرية للأخوين بربروس، وتتميز بغابات الكورنيش الكثيفة والكهوف العجيبة المطلة على البحر.",
    "fact_status": "legacy-local-fact"
  },
  "Sétif": {
    "code": 19,
    "name_ar": "سطيف",
    "name_fr": "Sétif",
    "capital": "Sétif",
    "region": "East",
    "created": 1984,
    "communes_count": 60,
    "dairas_count": 20,
    "mother_wilaya": null,
    "official_source": "https://www.joradp.dz/FTP/jo-francais/2026/F2026025.pdf",
    "fact": "Capital of the sparkling High Plateaus, rich in agricultural crops, and home to the UNESCO World Heritage Roman city of Cuicul (Djemila).",
    "fact_fr": "Capitale des Hauts Plateaux scintillants, riche en cultures agricoles, et abritant la ville romaine de Cuicul (Djemila), classée au patrimoine mondial.",
    "fact_ar": "عاصمة الهضاب العليا المتلألئة، تزخر بالمحاصيل الزراعية وتضم مدينة كويكول (جميلة) الرومانية المصنفة ضمن التراث العالمي.",
    "fact_status": "legacy-local-fact"
  },
  "Saïda": {
    "code": 20,
    "name_ar": "سعيدة",
    "name_fr": "Saïda",
    "capital": "Saïda",
    "region": "West",
    "created": 1984,
    "communes_count": 16,
    "dairas_count": 6,
    "mother_wilaya": null,
    "official_source": "https://www.joradp.dz/FTP/jo-francais/2026/F2026025.pdf",
    "fact": "City of Eagles, known for its pristine nature, it is a major hub for thermal and natural mineral waters in the west.",
    "fact_fr": "Ville des Aigles, connue pour sa nature vierge, c'est un pôle majeur des eaux thermales et minérales naturelles de l'ouest.",
    "fact_ar": "مدينة العقبان، طبيعة عذراء ساحرة، وتعتبر قطباً للمياه المعدنية الحارة والطبيعية في الغرب الجزائري.",
    "fact_status": "legacy-local-fact"
  },
  "Skikda": {
    "code": 21,
    "name_ar": "سكيكدة",
    "name_fr": "Skikda",
    "capital": "Skikda",
    "region": "North",
    "created": 1984,
    "communes_count": 38,
    "dairas_count": 13,
    "mother_wilaya": null,
    "official_source": "https://www.joradp.dz/FTP/jo-francais/2026/F2026025.pdf",
    "fact": "Ancient Rusicada, a global petrochemical hub, characterized by long coastlines, a Roman theater, and its highly reputed strawberries.",
    "fact_fr": "L'ancienne Rusicada, un pôle pétrochimique mondial, caractérisée par de longues côtes, un théâtre romain et ses fraises très réputées.",
    "fact_ar": "روسيكادا القديمة، قطب بتروكيماوي عالمي، تتميز بسواحلها الطويلة، ومسرحها الروماني، والفراولة ذائعة الصيت.",
    "fact_status": "legacy-local-fact"
  },
  "Sidi Bel Abbès": {
    "code": 22,
    "name_ar": "سيدي بلعباس",
    "name_fr": "Sidi Bel Abbès",
    "capital": "Sidi Bel Abbès",
    "region": "West",
    "created": 1984,
    "communes_count": 52,
    "dairas_count": 15,
    "mother_wilaya": null,
    "official_source": "https://www.joradp.dz/FTP/jo-francais/2026/F2026025.pdf",
    "fact": "Capital of the Mekerra river, known for its beautiful fertile fields and functioning as a major agricultural and electronic hub.",
    "fact_fr": "Capitale de la rivière Mekerra, connue pour ses beaux champs fertiles et fonctionnant comme un centre agricole et électronique majeur.",
    "fact_ar": "عاصمة المكرة، تحولت إلى قطب زراعي وإلكتروني هام وتتميز ببساتينها وحقولها الخصبة.",
    "fact_status": "legacy-local-fact"
  },
  "Annaba": {
    "code": 23,
    "name_ar": "عنابة",
    "name_fr": "Annaba",
    "capital": "Annaba",
    "region": "North",
    "created": 1984,
    "communes_count": 12,
    "dairas_count": 6,
    "mother_wilaya": null,
    "official_source": "https://www.joradp.dz/FTP/jo-francais/2026/F2026025.pdf",
    "fact": "Ancient Bône, the fourth largest city, home to the ruins of Hippo Regius and St. Augustine's Basilica, and a massive industrial pole.",
    "fact_fr": "L'ancienne Bône, la quatrième plus grande ville, abritant les ruines d'Hippone et la basilique Saint-Augustin, et un pôle industriel majeur.",
    "fact_ar": "بونة القديمة، رابع أكبر مدينة، تضم آثار هيبون وكنيسة القديس أوغسطين، وتعتبر قطباً صناعياً كبيراً (مركب الحجار).",
    "fact_status": "legacy-local-fact"
  },
  "Guelma": {
    "code": 24,
    "name_ar": "قالمة",
    "name_fr": "Guelma",
    "capital": "Guelma",
    "region": "East",
    "created": 1984,
    "communes_count": 34,
    "dairas_count": 10,
    "mother_wilaya": null,
    "official_source": "https://www.joradp.dz/FTP/jo-francais/2026/F2026025.pdf",
    "fact": "Roman Calama, famous for its restored Roman theater, wide agricultural lands, and the boiling thermal waterfalls of Hammam Debagh.",
    "fact_fr": "La romaine Calama, célèbre pour son théâtre romain restauré, ses vastes terres agricoles et les cascades thermales bouillonnantes de Hammam Debagh.",
    "fact_ar": "مدينة كالاما الرومانية، تشتهر بالمسرح الروماني المرمم والساحات الفلاحية الواسعة وشلالات حمام الدباغ الحرارية العجيبة.",
    "fact_status": "legacy-local-fact"
  },
  "Constantine": {
    "code": 25,
    "name_ar": "قسنطينة",
    "name_fr": "Constantine",
    "capital": "Constantine",
    "region": "East",
    "created": 1984,
    "communes_count": 12,
    "dairas_count": 7,
    "mother_wilaya": null,
    "official_source": "https://www.joradp.dz/FTP/jo-francais/2026/F2026025.pdf",
    "fact": "Ancient Cirta, City of the Old Rock and cultural capital, built on a limestone plateau surrounded by the Rhummel gorge and linked by suspension bridges.",
    "fact_fr": "L'ancienne Cirta, ville du vieux rocher et capitale culturelle, construite sur un plateau calcaire entouré des gorges du Rhummel et relié par des ponts suspendus.",
    "fact_ar": "سيرتا قديماً، مدينة الصخر العتيق وعاصمة الثقافة، شيدت على صخرة كلسية يطوقها وادي الرمال وتربطها جسور معلقة.",
    "fact_status": "legacy-local-fact"
  },
  "Médéa": {
    "code": 26,
    "name_ar": "المدية",
    "name_fr": "Médéa",
    "capital": "Médéa",
    "region": "North",
    "created": 1984,
    "communes_count": 43,
    "dairas_count": 13,
    "mother_wilaya": null,
    "official_source": "https://www.joradp.dz/FTP/jo-francais/2026/F2026025.pdf",
    "fact": "Capital of the Ottoman Titteri Beylik, distinguished by its vineyards and strategic mountainous location in the Tell Atlas.",
    "fact_fr": "Capitale du Beylik ottoman du Titteri, distinguée par ses vignobles et son emplacement montagneux stratégique dans l'Atlas tellien.",
    "fact_ar": "عاصمة بايلك التيطري العثماني، تمتاز ببساتين الكروم وموقعها الجبلي الاستراتيجي في الأطلس التلي.",
    "fact_status": "legacy-local-fact"
  },
  "Mostaganem": {
    "code": 27,
    "name_ar": "مستغانم",
    "name_fr": "Mostaganem",
    "capital": "Mostaganem",
    "region": "West",
    "created": 1984,
    "communes_count": 32,
    "dairas_count": 10,
    "mother_wilaya": null,
    "official_source": "https://www.joradp.dz/FTP/jo-francais/2026/F2026025.pdf",
    "fact": "Metropolis of the Dahra region and birthplace of distinct Sufi orders, an agricultural coastal city rich in Ottoman historical landmarks.",
    "fact_fr": "Métropole de la région du Dahra et berceau de confréries soufies distinctes, une ville côtière agricole riche en repères historiques ottomans.",
    "fact_ar": "حاضرة الظهرة ومسقط رأس الصوفية المتميزة، مدينة ساحلية فلاحية غنية بالمعالم التاريخية العثمانية.",
    "fact_status": "legacy-local-fact"
  },
  "M'Sila": {
    "code": 28,
    "name_ar": "المسيلة",
    "name_fr": "M'Sila",
    "capital": "M'Sila",
    "region": "Central",
    "created": 1984,
    "communes_count": 24,
    "dairas_count": 7,
    "mother_wilaya": null,
    "official_source": "https://www.joradp.dz/FTP/jo-francais/2026/F2026025.pdf",
    "fact": "Capital of the Hodna region, housing Al Qal'a of Beni Hammad (UNESCO site) and featuring a diverse geography of mountains, steppes, and chotts.",
    "fact_fr": "Capitale de la région du Hodna, abritant la Kalâa des Béni Hammad (site UNESCO) et présentant une géographie diversifiée de montagnes, de steppes et de chotts.",
    "fact_ar": "عاصمة الحضنة، تحتضن قلعة بني حماد (تراث عالمي) وتتميز بتنوعها الجغرافي بين الجبال والسهوب وشط الحضنة.",
    "fact_status": "legacy-local-fact"
  },
  "Mascara": {
    "code": 29,
    "name_ar": "معسكر",
    "name_fr": "Mascara",
    "capital": "Mascara",
    "region": "West",
    "created": 1984,
    "communes_count": 47,
    "dairas_count": 16,
    "mother_wilaya": null,
    "official_source": "https://www.joradp.dz/FTP/jo-francais/2026/F2026025.pdf",
    "fact": "Capital of Emir Abdelkader's state, a peaceful city of fertile plains, lush vineyards, and generous agricultural nature.",
    "fact_fr": "Capitale de l'État de l'Émir Abdelkader, une ville paisible de plaines fertiles, de vignobles luxuriants et d'une nature agricole généreuse.",
    "fact_ar": "عاصمة دولة الأمير عبد القادر، مدينة السهول الخصبة والكروم والطبيعة الفلاحية السخية.",
    "fact_status": "legacy-local-fact"
  },
  "Ouargla": {
    "code": 30,
    "name_ar": "ورقلة",
    "name_fr": "Ouargla",
    "capital": "Ouargla",
    "region": "South",
    "created": 1984,
    "communes_count": 8,
    "dairas_count": 5,
    "mother_wilaya": null,
    "official_source": "https://www.joradp.dz/FTP/jo-francais/2026/F2026025.pdf",
    "fact": "Capital of Oases and Black Gold, one of the oldest Saharan cities, containing the Hassi Messaoud oil basin, the largest in the country.",
    "fact_fr": "Capitale des oasis et de l'or noir, l'une des plus anciennes villes sahariennes, contenant le bassin pétrolier de Hassi Messaoud, le plus grand du pays.",
    "fact_ar": "عاصمة الواحات والذهب الأسود، من أقدم المدن الصحراوية، تضم حوض حاسي مسعود النفطي الأكبر في البلاد.",
    "fact_status": "legacy-local-fact"
  },
  "Oran": {
    "code": 31,
    "name_ar": "وهران",
    "name_fr": "Oran",
    "capital": "Oran",
    "region": "West",
    "created": 1984,
    "communes_count": 26,
    "dairas_count": 9,
    "mother_wilaya": null,
    "official_source": "https://www.joradp.dz/FTP/jo-francais/2026/F2026025.pdf",
    "fact": "El Bahia (The Radiant), the second capital, founded by Andalusians, marked by diverse historical eras, home to Fort Santa Cruz.",
    "fact_fr": "El Bahia (La Radieuse), la deuxième capitale, fondée par les Andalous, marquée par diverses époques historiques, abritant le Fort Santa Cruz.",
    "fact_ar": "الباهية، العاصمة الثانية، أسسها الأندلسيون وشهدت تعاقب حضارات مختلفة، وتضم حصن سانتا كروز العريق.",
    "fact_status": "legacy-local-fact"
  },
  "El Bayadh": {
    "code": 32,
    "name_ar": "البيض",
    "name_fr": "El Bayadh",
    "capital": "El Bayadh",
    "region": "West",
    "created": 1984,
    "communes_count": 15,
    "dairas_count": 5,
    "mother_wilaya": null,
    "official_source": "https://www.joradp.dz/FTP/jo-francais/2026/F2026025.pdf",
    "fact": "Situated on the Amour Range, a national reservoir of groundwater and livestock, rich in ancient Ksours and rock engravings.",
    "fact_fr": "Située sur le massif de l'Amour, un réservoir national d'eaux souterraines et de bétail, riche en anciens ksour et gravures rupestres.",
    "fact_ar": "تتربع على جبال عمور، وهي خزان وطني للمياه الجوفية والثروة الحيوانية، وتزخر بالقصور والنقوش الصخرية القديمة.",
    "fact_status": "legacy-local-fact"
  },
  "Illizi": {
    "code": 33,
    "name_ar": "إليزي",
    "name_fr": "Illizi",
    "capital": "Illizi",
    "region": "South",
    "created": 1984,
    "communes_count": 4,
    "dairas_count": 4,
    "mother_wilaya": null,
    "official_source": "https://www.joradp.dz/FTP/jo-francais/2026/F2026025.pdf",
    "fact": "Pearl of the Tassili, possessing the world's largest open-air museum of prehistoric rock art (UNESCO World Heritage).",
    "fact_fr": "Perle du Tassili, possédant le plus grand musée à ciel ouvert d'art rupestre préhistorique au monde (patrimoine mondial de l'UNESCO).",
    "fact_ar": "جوهرة التاسيلي، تمتلك أكبر متحف مفتوح في العالم للرسومات الصخرية التي تعود لعصور ما قبل التاريخ (تراث عالمي).",
    "fact_status": "legacy-local-fact"
  },
  "Bordj Bou Arreridj": {
    "code": 34,
    "name_ar": "برج بوعريريج",
    "name_fr": "Bordj Bou Arreridj",
    "capital": "Bordj Bou Arreridj",
    "region": "East",
    "created": 1984,
    "communes_count": 34,
    "dairas_count": 10,
    "mother_wilaya": null,
    "official_source": "https://www.joradp.dz/FTP/jo-francais/2026/F2026025.pdf",
    "fact": "Capital of the Bibans, a crucial link between East and Center, evolved into Algeria's primary industrial hub for electronics.",
    "fact_fr": "Capitale des Bibans, lien crucial entre l'Est et le Centre, devenue le principal pôle industriel algérien pour l'électronique.",
    "fact_ar": "عاصمة البيبان، همزة وصل بين الشرق والوسط، وتطورت لتصبح القطب الصناعي الأول للإلكترونيات في الجزائر.",
    "fact_status": "legacy-local-fact"
  },
  "Boumerdès": {
    "code": 35,
    "name_ar": "بومرداس",
    "name_fr": "Boumerdès",
    "capital": "Boumerdès",
    "region": "North",
    "created": 1984,
    "communes_count": 32,
    "dairas_count": 9,
    "mother_wilaya": null,
    "official_source": "https://www.joradp.dz/FTP/jo-francais/2026/F2026025.pdf",
    "fact": "City of Science, hosting numerous national institutes and universities, featuring a beautiful coastline adjacent to Algiers.",
    "fact_fr": "Ville des sciences, accueillant de nombreux instituts et universités nationaux, avec un magnifique littoral adjacent à Alger.",
    "fact_ar": "مدينة العلم، تحضن العديد من المعاهد والجامعات الوطنية، وتمتاز بساحلها الجميل المحاذي للجزائر العاصمة.",
    "fact_status": "legacy-local-fact"
  },
  "El Tarf": {
    "code": 36,
    "name_ar": "الطارف",
    "name_fr": "El Tarf",
    "capital": "El Tarf",
    "region": "East",
    "created": 1984,
    "communes_count": 24,
    "dairas_count": 7,
    "mother_wilaya": null,
    "official_source": "https://www.joradp.dz/FTP/jo-francais/2026/F2026025.pdf",
    "fact": "The green lung of the East, home to El Kala National Park, rich in lakes, unique ecosystems, and coral reefs.",
    "fact_fr": "Le poumon vert de l'Est, abritant le parc national d'El Kala, riche en lacs, écosystèmes uniques et récifs coralliens.",
    "fact_ar": "الرئة الخضراء للشرق، تضم حظيرة القالة الوطنية الغنية بالبحيرات والأنظمة البيئية الفريدة والشعاب المرجانية.",
    "fact_status": "legacy-local-fact"
  },
  "Tindouf": {
    "code": 37,
    "name_ar": "تندوف",
    "name_fr": "Tindouf",
    "capital": "Tindouf",
    "region": "South",
    "created": 1984,
    "communes_count": 2,
    "dairas_count": 1,
    "mother_wilaya": null,
    "official_source": "https://www.joradp.dz/FTP/jo-francais/2026/F2026025.pdf",
    "fact": "Gateway to the southwest, a historical crossroads for trade caravans, housing the Gara Djebilet iron mine, the largest in Africa.",
    "fact_fr": "Porte du sud-ouest, carrefour historique des caravanes commerciales, abritant la mine de fer de Gara Djebilet, la plus grande d'Afrique.",
    "fact_ar": "بوابة الجنوب الغربي، نقطة التقاء تاريخية لقوافل التجارة، وتحتوي على منجم غار جبيلات للحديد، الأكبر إفريقيا.",
    "fact_status": "legacy-local-fact"
  },
  "Tissemsilt": {
    "code": 38,
    "name_ar": "تيسمسيلت",
    "name_fr": "Tissemsilt",
    "capital": "Tissemsilt",
    "region": "West",
    "created": 1984,
    "communes_count": 22,
    "dairas_count": 8,
    "mother_wilaya": null,
    "official_source": "https://www.joradp.dz/FTP/jo-francais/2026/F2026025.pdf",
    "fact": "Famous for the Théniet El Had National Park (cedar forests), acting as a green bridge between the Ouarsenis mountains and the steppes.",
    "fact_fr": "Célèbre pour le parc national de Théniet El Had (forêts de cèdres), servant de pont vert entre les montagnes de l'Ouarsenis et les steppes.",
    "fact_ar": "تشتهر بالحظيرة الوطنية لثنية الحد (غابة الأرز)، وتعتبر همزة وصل خضراء بين جبال الونشريس والسهوب.",
    "fact_status": "legacy-local-fact"
  },
  "El Oued": {
    "code": 39,
    "name_ar": "الوادي",
    "name_fr": "El Oued",
    "capital": "El Oued",
    "region": "South",
    "created": 1984,
    "communes_count": 22,
    "dairas_count": 10,
    "mother_wilaya": null,
    "official_source": "https://www.joradp.dz/FTP/jo-francais/2026/F2026025.pdf",
    "fact": "City of a Thousand and One Domes, distinguished by unique Saharan architecture, palm cultivation, and agriculture in the Grand Erg Oriental.",
    "fact_fr": "Ville aux mille et une coupoles, caractérisée par une architecture saharienne unique, la culture des palmiers et l'agriculture dans le Grand Erg Oriental.",
    "fact_ar": "مدينة الألف قبة وقبة، تتميز بعمارتها الصحراوية الفريدة وزراعة النخيل والفلاحة في رمال العرق الشرقي الكبير.",
    "fact_status": "legacy-local-fact"
  },
  "Khenchela": {
    "code": 40,
    "name_ar": "خنشلة",
    "name_fr": "Khenchela",
    "capital": "Khenchela",
    "region": "East",
    "created": 1984,
    "communes_count": 21,
    "dairas_count": 8,
    "mother_wilaya": null,
    "official_source": "https://www.joradp.dz/FTP/jo-francais/2026/F2026025.pdf",
    "fact": "Roman Mascula, fortress of the Aurès mountains, famous for agriculture and the Roman baths of Essalihine still in use today.",
    "fact_fr": "La romaine Mascula, forteresse des monts Aurès, célèbre pour son agriculture et les thermes romains d'Essalihine toujours en usage aujourd'hui.",
    "fact_ar": "مدينة ماسكولا الرومانية، حصن جبال الأوراس، تشتهر بالزراعة وحمامات الصالحين الرومانية التي لا تزال قيد الاستخدام.",
    "fact_status": "legacy-local-fact"
  },
  "Souk Ahras": {
    "code": 41,
    "name_ar": "سوق أهراس",
    "name_fr": "Souk Ahras",
    "capital": "Souk Ahras",
    "region": "East",
    "created": 1984,
    "communes_count": 26,
    "dairas_count": 10,
    "mother_wilaya": null,
    "official_source": "https://www.joradp.dz/FTP/jo-francais/2026/F2026025.pdf",
    "fact": "Ancient Thagaste, birthplace of St. Augustine, a city of olive trees, magical mountain nature, and rich agricultural heritage.",
    "fact_fr": "L'ancienne Thagaste, lieu de naissance de Saint Augustin, une ville d'oliviers, de nature montagneuse magique et d'un riche patrimoine agricole.",
    "fact_ar": "طاغاست القديمة ومسقط رأس القديس أوغسطين، مدينة الزيتون والطبيعة الجبلية الساحرة وتراثها الزراعي الغني.",
    "fact_status": "legacy-local-fact"
  },
  "Tipaza": {
    "code": 42,
    "name_ar": "تيبازة",
    "name_fr": "Tipaza",
    "capital": "Tipaza",
    "region": "North",
    "created": 1984,
    "communes_count": 28,
    "dairas_count": 10,
    "mother_wilaya": null,
    "official_source": "https://www.joradp.dz/FTP/jo-francais/2026/F2026025.pdf",
    "fact": "Home to seaside Roman and Phoenician ruins (UNESCO site), its natural beauty profoundly inspired the writer Albert Camus.",
    "fact_fr": "Abritant des ruines romaines et phéniciennes en bord de mer (site de l'UNESCO), sa beauté naturelle a profondément inspiré l'écrivain Albert Camus.",
    "fact_ar": "موطن الآثار الرومانية والفينيقية المطلة على البحر (تراث عالمي)، ألهمت الكاتب ألبير كامو بجمال طبيعتها.",
    "fact_status": "legacy-local-fact"
  },
  "Mila": {
    "code": 43,
    "name_ar": "ميلة",
    "name_fr": "Mila",
    "capital": "Mila",
    "region": "East",
    "created": 1984,
    "communes_count": 32,
    "dairas_count": 13,
    "mother_wilaya": null,
    "official_source": "https://www.joradp.dz/FTP/jo-francais/2026/F2026025.pdf",
    "fact": "Ancient Milev, housing the first mosque built in Algeria (Abu al-Muhajir Dinar) and the country's largest water dam (Beni Haroun).",
    "fact_fr": "L'ancienne Milev, abritant la première mosquée construite en Algérie (Abu al-Muhajir Dinar) et le plus grand barrage d'eau du pays (Beni Haroun).",
    "fact_ar": "ميلاف القديمة، تحوي أول مسجد بني في الجزائر (أبو المهاجر دينار) وأكبر سد مائي في البلاد (سد بني هارون).",
    "fact_status": "legacy-local-fact"
  },
  "Aïn Defla": {
    "code": 44,
    "name_ar": "عين الدفلى",
    "name_fr": "Aïn Defla",
    "capital": "Aïn Defla",
    "region": "North",
    "created": 1984,
    "communes_count": 36,
    "dairas_count": 14,
    "mother_wilaya": null,
    "official_source": "https://www.joradp.dz/FTP/jo-francais/2026/F2026025.pdf",
    "fact": "Roman Oppidum Novum, highly agricultural within the Chelif plain, considered Algeria's food basket and leading potato producer.",
    "fact_fr": "Oppidum Novum romain, très agricole dans la plaine du Chelif, considérée comme le grenier de l'Algérie et le premier producteur de pommes de terre.",
    "fact_ar": "مدينة أوبيدوم نوفوم، تتمتع بطابع فلاحي بامتياز في سهل الشلف، وتعتبر سلة غذاء الجزائر الأولى في إنتاج البطاطا.",
    "fact_status": "legacy-local-fact"
  },
  "Naâma": {
    "code": 45,
    "name_ar": "النعامة",
    "name_fr": "Naâma",
    "capital": "Naâma",
    "region": "West",
    "created": 1984,
    "communes_count": 12,
    "dairas_count": 7,
    "mother_wilaya": null,
    "official_source": "https://www.joradp.dz/FTP/jo-francais/2026/F2026025.pdf",
    "fact": "Gateway to the western Sahara, famous for the Tiout oasis and its historical Ksar, historically populated by the ostriches it is named after.",
    "fact_fr": "Porte du Sahara occidental, célèbre pour l'oasis de Tiout et son Ksar historique, historiquement peuplée par les autruches dont elle tire son nom.",
    "fact_ar": "بوابة الصحراء الغربية، تشتهر بواحة تيوث وقلعتها التاريخية، وتنتشر فيها طيور النعام التي سميت الولاية تيمناً بها.",
    "fact_status": "legacy-local-fact"
  },
  "Aïn Témouchent": {
    "code": 46,
    "name_ar": "عين تموشنت",
    "name_fr": "Aïn Témouchent",
    "capital": "Aïn Témouchent",
    "region": "West",
    "created": 1984,
    "communes_count": 28,
    "dairas_count": 8,
    "mother_wilaya": null,
    "official_source": "https://www.joradp.dz/FTP/jo-francais/2026/F2026025.pdf",
    "fact": "Pearl of the western coast, boasting magical beaches, beautiful coastal landscapes, and relaxing thermal spas.",
    "fact_fr": "Perle de la côte ouest, offrant des plages magiques, de magnifiques paysages côtiers et des stations thermales relaxantes.",
    "fact_ar": "لؤلؤة الساحل الغربي، تزخر بشواطئ ساحرة ومحطات معدنية ومناظر طبيعية خلابة.",
    "fact_status": "legacy-local-fact"
  },
  "Ghardaïa": {
    "code": 47,
    "name_ar": "غرداية",
    "name_fr": "Ghardaïa",
    "capital": "Ghardaïa",
    "region": "South",
    "created": 1984,
    "communes_count": 10,
    "dairas_count": 8,
    "mother_wilaya": null,
    "official_source": "https://www.joradp.dz/FTP/jo-francais/2026/F2026025.pdf",
    "fact": "Jewel of the M'zab Valley (UNESCO site), fascinating the world with its unique architectural layout and precise social organization across 5 Ksours.",
    "fact_fr": "Joyau de la vallée du M'zab (site de l'UNESCO), fascinant le monde par son aménagement architectural unique et son organisation sociale précise à travers 5 ksour.",
    "fact_ar": "جوهرة وادي ميزاب (تراث عالمي)، تبهر العالم بنظامها المعماري الفريد والتنظيم الاجتماعي الدقيق بقصورها الخمسة.",
    "fact_status": "legacy-local-fact"
  },
  "Relizane": {
    "code": 48,
    "name_ar": "غليزان",
    "name_fr": "Relizane",
    "capital": "Relizane",
    "region": "West",
    "created": 1984,
    "communes_count": 38,
    "dairas_count": 13,
    "mother_wilaya": null,
    "official_source": "https://www.joradp.dz/FTP/jo-francais/2026/F2026025.pdf",
    "fact": "Ancient Mina, a vital transit region and an agricultural/commercial hub relying on the lower Chelif basin and the Mina plain.",
    "fact_fr": "L'ancienne Mina, une région de transit vitale et un carrefour agricole/commercial dépendant du bassin inférieur du Chelif et de la plaine de la Mina.",
    "fact_ar": "مدينة مينا القديمة، منطقة عبور حيوية وقطب زراعي وتجاري يعتمد على حوض الشلف السفلي وسهل مينا.",
    "fact_status": "legacy-local-fact"
  },
  "Timimoun": {
    "code": 49,
    "name_ar": "تيميمون",
    "name_fr": "Timimoun",
    "capital": "Timimoun",
    "region": "South",
    "created": 2019,
    "communes_count": 10,
    "dairas_count": 4,
    "mother_wilaya": "Adrar",
    "official_source": "https://www.joradp.dz/FTP/jo-francais/2026/F2026025.pdf",
    "fact": "The Red Oasis, pearl of the Gourara region, famous for its red clay Andalusian-style architecture and the Sboue festival.",
    "fact_fr": "L'Oasis Rouge, perle de la région du Gourara, célèbre pour son architecture de style andalou en argile rouge et son festival du Sboue.",
    "fact_ar": "الواحة الحمراء، لؤلؤة منطقة قورارة، تشتهر بعمارتها الطينية الأندلسية ومهرجان أسبوع المولد النبوي الشريف.",
    "fact_status": "legacy-local-fact"
  },
  "Bordj Badji Mokhtar": {
    "code": 50,
    "name_ar": "برج باجي مختار",
    "name_fr": "Bordj Badji Mokhtar",
    "capital": "Bordj Badji Mokhtar",
    "region": "South",
    "created": 2019,
    "communes_count": 2,
    "dairas_count": 1,
    "mother_wilaya": "Adrar",
    "official_source": "https://www.joradp.dz/FTP/jo-francais/2026/F2026025.pdf",
    "fact": "A strategic border province in the far south with Mali, known for barter trade and as a stronghold of Hassaniya and Tuareg culture.",
    "fact_fr": "Une province frontalière stratégique de l'extrême sud avec le Mali, connue pour le commerce de troc et comme bastion de la culture hassaniya et touarègue.",
    "fact_ar": "ولاية حدودية استراتيجية أقصى الجنوب مع مالي، تشتهر بتجارة المقايضة وتعتبر معقلاً للثقافة الحسانية والطوارقية.",
    "fact_status": "legacy-local-fact"
  },
  "Ouled Djellal": {
    "code": 51,
    "name_ar": "أولاد جلال",
    "name_fr": "Ouled Djellal",
    "capital": "Ouled Djellal",
    "region": "East",
    "created": 2019,
    "communes_count": 6,
    "dairas_count": 2,
    "mother_wilaya": "Biskra",
    "official_source": "https://www.joradp.dz/FTP/jo-francais/2026/F2026025.pdf",
    "fact": "A newly created steppe/Saharan province, home to the 'Ouled Djellal' sheep breed globally renowned for high-quality meat.",
    "fact_fr": "Une province steppique/saharienne nouvellement créée, berceau de la race ovine 'Ouled Djellal' mondialement reconnue pour sa viande de haute qualité.",
    "fact_ar": "ولاية سهبية صحراوية حديثة، موطن سلالة الغنم 'الجلالية' ذات الشهرة العالمية في جودة اللحوم.",
    "fact_status": "legacy-local-fact"
  },
  "Béni Abbès": {
    "code": 52,
    "name_ar": "بني عباس",
    "name_fr": "Béni Abbès",
    "capital": "Béni Abbès",
    "region": "South",
    "created": 2019,
    "communes_count": 10,
    "dairas_count": 6,
    "mother_wilaya": "Béchar",
    "official_source": "https://www.joradp.dz/FTP/jo-francais/2026/F2026025.pdf",
    "fact": "Jewel of the Saoura, uniquely nestled between the sand dunes of the Grand Erg Occidental and the Saoura valley, with a rich history.",
    "fact_fr": "Joyau de la Saoura, niché de manière unique entre les dunes de sable du Grand Erg Occidental et la vallée de la Saoura, avec une histoire riche.",
    "fact_ar": "جوهرة الساورة، تتميز بتموقعها الساحر بين الكثبان الرملية (العرق الغربي الكبير) ووادي الساورة، وتاريخها العريق.",
    "fact_status": "legacy-local-fact"
  },
  "In Salah": {
    "code": 53,
    "name_ar": "عين صالح",
    "name_fr": "In Salah",
    "capital": "In Salah",
    "region": "South",
    "created": 2019,
    "communes_count": 3,
    "dairas_count": 2,
    "mother_wilaya": "Tamanrasset",
    "official_source": "https://www.joradp.dz/FTP/jo-francais/2026/F2026025.pdf",
    "fact": "Located in the deep Sahara, a major natural gas hub characterized by palm groves fighting the encroaching desert sands.",
    "fact_fr": "Située dans le Sahara profond, une plaque tournante majeure du gaz naturel caractérisée par des palmeraies luttant contre l'avancée des sables du désert.",
    "fact_ar": "تقع في قلب الصحراء، تعد أحد أقطاب الغاز الطبيعي وتتميز بغابات النخيل الزاحفة عليها رمال الصحراء.",
    "fact_status": "legacy-local-fact"
  },
  "In Guezzam": {
    "code": 54,
    "name_ar": "عين قزام",
    "name_fr": "In Guezzam",
    "capital": "In Guezzam",
    "region": "South",
    "created": 2019,
    "communes_count": 2,
    "dairas_count": 2,
    "mother_wilaya": "Tamanrasset",
    "official_source": "https://www.joradp.dz/FTP/jo-francais/2026/F2026025.pdf",
    "fact": "The extreme southern border point with Niger, serving as a continental trade crossing and boasting untouched Saharan landscapes.",
    "fact_fr": "Le point frontalier sud extrême avec le Niger, servant de carrefour commercial continental et offrant des paysages sahariens vierges.",
    "fact_ar": "أقصى نقطة في الحدود الجنوبية مع النيجر، تعتبر معبراً تجارياً قارياً وتزخر بمناظر طبيعية صحراوية عذراء.",
    "fact_status": "legacy-local-fact"
  },
  "Touggourt": {
    "code": 55,
    "name_ar": "توقرت",
    "name_fr": "Touggourt",
    "capital": "Touggourt",
    "region": "South",
    "created": 2019,
    "communes_count": 13,
    "dairas_count": 5,
    "mother_wilaya": "Ouargla",
    "official_source": "https://www.joradp.dz/FTP/jo-francais/2026/F2026025.pdf",
    "fact": "Historical capital of the Oued Righ valley, it is a crucial basin for dates and abundant groundwater.",
    "fact_fr": "Capitale historique de la vallée de l'Oued Righ, c'est un bassin crucial pour les dattes et les eaux souterraines abondantes.",
    "fact_ar": "عاصمة وادي ريغ التاريخية، وتعد حوضاً هاماً للتمور والمياه الجوفية الوفيرة.",
    "fact_status": "legacy-local-fact"
  },
  "Djanet": {
    "code": 56,
    "name_ar": "جانت",
    "name_fr": "Djanet",
    "capital": "Djanet",
    "region": "South",
    "created": 2019,
    "communes_count": 2,
    "dairas_count": 1,
    "mother_wilaya": "Illizi",
    "official_source": "https://www.joradp.dz/FTP/jo-francais/2026/F2026025.pdf",
    "fact": "Bride of the Tassili, a magical mountain oasis near the Libyan border, serving as Algeria's premier base for Saharan eco-tourism.",
    "fact_fr": "La mariée du Tassili, une oasis de montagne magique près de la frontière libyenne, servant de base principale à l'écotourisme saharien en Algérie.",
    "fact_ar": "عروس التاسيلي، واحة جبلية ساحرة على الحدود الليبية، وتعد أهم قاعدة للسياحة البيئية الصحراوية في الجزائر.",
    "fact_status": "legacy-local-fact"
  },
  "El M'Ghair": {
    "code": 57,
    "name_ar": "المغير",
    "name_fr": "El M'Ghair",
    "capital": "El M'Ghair",
    "region": "South",
    "created": 2019,
    "communes_count": 8,
    "dairas_count": 2,
    "mother_wilaya": "El Oued",
    "official_source": "https://www.joradp.dz/FTP/jo-francais/2026/F2026025.pdf",
    "fact": "Gateway to the southeast in the heart of Oued Righ, famous for exporting premium dates and its large salt lakes (Chotts).",
    "fact_fr": "Porte du sud-est au cœur de l'Oued Righ, célèbre pour l'exportation de dattes de première qualité et ses grands lacs salés (Chotts).",
    "fact_ar": "بوابة الجنوب الشرقي، تقع بقلب وادي ريغ، تشتهر بإنتاج وتصدير أجود أنواع التمور والبحيرات المالحة (الشطوط).",
    "fact_status": "legacy-local-fact"
  },
  "El Meniaa": {
    "code": 58,
    "name_ar": "المنيعة",
    "name_fr": "El Meniaa",
    "capital": "El Meniaa",
    "region": "South",
    "created": 2019,
    "communes_count": 3,
    "dairas_count": 1,
    "mother_wilaya": "Ghardaïa",
    "official_source": "https://www.joradp.dz/FTP/jo-francais/2026/F2026025.pdf",
    "fact": "Also called El Goléa, a lush oasis with fresh water, beautifully dominated by a historical citadel on a mountain.",
    "fact_fr": "Aussi appelée El Goléa, une oasis luxuriante d'eau douce, magnifiquement dominée par une citadelle historique sur une montagne.",
    "fact_ar": "تسمى أيضاً القليعة، واحة غناء ذات مياه عذبة، يحتضن جبلها القلعة التاريخية الخلابة.",
    "fact_status": "legacy-local-fact"
  },
  "Aflou": {
    "code": 59,
    "name_ar": "آفلو",
    "name_fr": "Aflou",
    "capital": "Aflou",
    "region": "Central",
    "created": 2026,
    "communes_count": 12,
    "dairas_count": 5,
    "mother_wilaya": "Laghouat",
    "official_source": "https://www.joradp.dz/FTP/jo-francais/2026/F2026025.pdf",
    "fact": "Wilaya 59, created by Law 26-06 of 4 April 2026 from territory previously administered by Laghouat. It contains 12 communes.",
    "fact_fr": "Wilaya n° 59, créée par la loi 26-06 du 4 avril 2026 à partir d'un territoire auparavant administré par la wilaya de Laghouat. Elle compte 12 communes.",
    "fact_ar": "الولاية رقم 59، أُنشئت بموجب القانون 26-06 المؤرخ في 4 أفريل 2026 من إقليم كان تابعاً لولاية الأغواط، وتضم 12 بلدية.",
    "fact_status": "official-reform-summary"
  },
  "Barika": {
    "code": 60,
    "name_ar": "بريكة",
    "name_fr": "Barika",
    "capital": "Barika",
    "region": "East",
    "created": 2026,
    "communes_count": 8,
    "dairas_count": 3,
    "mother_wilaya": "Batna",
    "official_source": "https://www.joradp.dz/FTP/jo-francais/2026/F2026025.pdf",
    "fact": "Wilaya 60, created by Law 26-06 of 4 April 2026 from territory previously administered by Batna. It contains 8 communes.",
    "fact_fr": "Wilaya n° 60, créée par la loi 26-06 du 4 avril 2026 à partir d'un territoire auparavant administré par la wilaya de Batna. Elle compte 8 communes.",
    "fact_ar": "الولاية رقم 60، أُنشئت بموجب القانون 26-06 المؤرخ في 4 أفريل 2026 من إقليم كان تابعاً لولاية باتنة، وتضم 8 بلدية.",
    "fact_status": "official-reform-summary"
  },
  "El Kantara": {
    "code": 61,
    "name_ar": "القنطرة",
    "name_fr": "El Kantara",
    "capital": "El Kantara",
    "region": "East",
    "created": 2026,
    "communes_count": 5,
    "dairas_count": 3,
    "mother_wilaya": "Biskra",
    "official_source": "https://www.joradp.dz/FTP/jo-francais/2026/F2026025.pdf",
    "fact": "Wilaya 61, created by Law 26-06 of 4 April 2026 from territory previously administered by Biskra. It contains 5 communes.",
    "fact_fr": "Wilaya n° 61, créée par la loi 26-06 du 4 avril 2026 à partir d'un territoire auparavant administré par la wilaya de Biskra. Elle compte 5 communes.",
    "fact_ar": "الولاية رقم 61، أُنشئت بموجب القانون 26-06 المؤرخ في 4 أفريل 2026 من إقليم كان تابعاً لولاية بسكرة، وتضم 5 بلدية.",
    "fact_status": "official-reform-summary"
  },
  "Bir El Ater": {
    "code": 62,
    "name_ar": "بئر العاتر",
    "name_fr": "Bir El Ater",
    "capital": "Bir El Ater",
    "region": "East",
    "created": 2026,
    "communes_count": 4,
    "dairas_count": 2,
    "mother_wilaya": "Tébessa",
    "official_source": "https://www.joradp.dz/FTP/jo-francais/2026/F2026025.pdf",
    "fact": "Wilaya 62, created by Law 26-06 of 4 April 2026 from territory previously administered by Tébessa. It contains 4 communes.",
    "fact_fr": "Wilaya n° 62, créée par la loi 26-06 du 4 avril 2026 à partir d'un territoire auparavant administré par la wilaya de Tébessa. Elle compte 4 communes.",
    "fact_ar": "الولاية رقم 62، أُنشئت بموجب القانون 26-06 المؤرخ في 4 أفريل 2026 من إقليم كان تابعاً لولاية تبسة، وتضم 4 بلدية.",
    "fact_status": "official-reform-summary"
  },
  "El Aricha": {
    "code": 63,
    "name_ar": "العريشة",
    "name_fr": "El Aricha",
    "capital": "El Aricha",
    "region": "West",
    "created": 2026,
    "communes_count": 4,
    "dairas_count": 2,
    "mother_wilaya": "Tlemcen",
    "official_source": "https://www.joradp.dz/FTP/jo-francais/2026/F2026025.pdf",
    "fact": "Wilaya 63, created by Law 26-06 of 4 April 2026 from territory previously administered by Tlemcen. It contains 4 communes.",
    "fact_fr": "Wilaya n° 63, créée par la loi 26-06 du 4 avril 2026 à partir d'un territoire auparavant administré par la wilaya de Tlemcen. Elle compte 4 communes.",
    "fact_ar": "الولاية رقم 63، أُنشئت بموجب القانون 26-06 المؤرخ في 4 أفريل 2026 من إقليم كان تابعاً لولاية تلمسان، وتضم 4 بلدية.",
    "fact_status": "official-reform-summary"
  },
  "Ksar Chellala": {
    "code": 64,
    "name_ar": "قصر الشلالة",
    "name_fr": "Ksar Chellala",
    "capital": "Ksar Chellala",
    "region": "West",
    "created": 2026,
    "communes_count": 6,
    "dairas_count": 2,
    "mother_wilaya": "Tiaret",
    "official_source": "https://www.joradp.dz/FTP/jo-francais/2026/F2026025.pdf",
    "fact": "Wilaya 64, created by Law 26-06 of 4 April 2026 from territory previously administered by Tiaret. It contains 6 communes.",
    "fact_fr": "Wilaya n° 64, créée par la loi 26-06 du 4 avril 2026 à partir d'un territoire auparavant administré par la wilaya de Tiaret. Elle compte 6 communes.",
    "fact_ar": "الولاية رقم 64، أُنشئت بموجب القانون 26-06 المؤرخ في 4 أفريل 2026 من إقليم كان تابعاً لولاية تيارت، وتضم 6 بلدية.",
    "fact_status": "official-reform-summary"
  },
  "Aïn Ouessara": {
    "code": 65,
    "name_ar": "عين وسارة",
    "name_fr": "Aïn Ouessara",
    "capital": "Aïn Ouessara",
    "region": "Central",
    "created": 2026,
    "communes_count": 10,
    "dairas_count": 4,
    "mother_wilaya": "Djelfa",
    "official_source": "https://www.joradp.dz/FTP/jo-francais/2026/F2026025.pdf",
    "fact": "Wilaya 65, created by Law 26-06 of 4 April 2026 from territory previously administered by Djelfa. It contains 10 communes.",
    "fact_fr": "Wilaya n° 65, créée par la loi 26-06 du 4 avril 2026 à partir d'un territoire auparavant administré par la wilaya de Djelfa. Elle compte 10 communes.",
    "fact_ar": "الولاية رقم 65، أُنشئت بموجب القانون 26-06 المؤرخ في 4 أفريل 2026 من إقليم كان تابعاً لولاية الجلفة، وتضم 10 بلدية.",
    "fact_status": "official-reform-summary"
  },
  "Messaad": {
    "code": 66,
    "name_ar": "مسعد",
    "name_fr": "Messaad",
    "capital": "Messaad",
    "region": "Central",
    "created": 2026,
    "communes_count": 8,
    "dairas_count": 2,
    "mother_wilaya": "Djelfa",
    "official_source": "https://www.joradp.dz/FTP/jo-francais/2026/F2026025.pdf",
    "fact": "Wilaya 66, created by Law 26-06 of 4 April 2026 from territory previously administered by Djelfa. It contains 8 communes.",
    "fact_fr": "Wilaya n° 66, créée par la loi 26-06 du 4 avril 2026 à partir d'un territoire auparavant administré par la wilaya de Djelfa. Elle compte 8 communes.",
    "fact_ar": "الولاية رقم 66، أُنشئت بموجب القانون 26-06 المؤرخ في 4 أفريل 2026 من إقليم كان تابعاً لولاية الجلفة، وتضم 8 بلدية.",
    "fact_status": "official-reform-summary"
  },
  "Ksar El Boukhari": {
    "code": 67,
    "name_ar": "قصر البخاري",
    "name_fr": "Ksar El Boukhari",
    "capital": "Ksar El Boukhari",
    "region": "North",
    "created": 2026,
    "communes_count": 21,
    "dairas_count": 6,
    "mother_wilaya": "Médéa",
    "official_source": "https://www.joradp.dz/FTP/jo-francais/2026/F2026025.pdf",
    "fact": "Wilaya 67, created by Law 26-06 of 4 April 2026 from territory previously administered by Médéa. It contains 21 communes.",
    "fact_fr": "Wilaya n° 67, créée par la loi 26-06 du 4 avril 2026 à partir d'un territoire auparavant administré par la wilaya de Médéa. Elle compte 21 communes.",
    "fact_ar": "الولاية رقم 67، أُنشئت بموجب القانون 26-06 المؤرخ في 4 أفريل 2026 من إقليم كان تابعاً لولاية المدية، وتضم 21 بلدية.",
    "fact_status": "official-reform-summary"
  },
  "Bou Saâda": {
    "code": 68,
    "name_ar": "بوسعادة",
    "name_fr": "Bou Saâda",
    "capital": "Bou Saâda",
    "region": "Central",
    "created": 2026,
    "communes_count": 23,
    "dairas_count": 8,
    "mother_wilaya": "M'Sila",
    "official_source": "https://www.joradp.dz/FTP/jo-francais/2026/F2026025.pdf",
    "fact": "Wilaya 68, created by Law 26-06 of 4 April 2026 from territory previously administered by M'Sila. It contains 23 communes.",
    "fact_fr": "Wilaya n° 68, créée par la loi 26-06 du 4 avril 2026 à partir d'un territoire auparavant administré par la wilaya de M'Sila. Elle compte 23 communes.",
    "fact_ar": "الولاية رقم 68، أُنشئت بموجب القانون 26-06 المؤرخ في 4 أفريل 2026 من إقليم كان تابعاً لولاية المسيلة، وتضم 23 بلدية.",
    "fact_status": "official-reform-summary"
  },
  "El Abiodh Sidi Cheikh": {
    "code": 69,
    "name_ar": "الأبيض سيدي الشيخ",
    "name_fr": "El Abiodh Sidi Cheikh",
    "capital": "El Abiodh Sidi Cheikh",
    "region": "West",
    "created": 2026,
    "communes_count": 7,
    "dairas_count": 3,
    "mother_wilaya": "El Bayadh",
    "official_source": "https://www.joradp.dz/FTP/jo-francais/2026/F2026025.pdf",
    "fact": "Wilaya 69, created by Law 26-06 of 4 April 2026 from territory previously administered by El Bayadh. It contains 7 communes.",
    "fact_fr": "Wilaya n° 69, créée par la loi 26-06 du 4 avril 2026 à partir d'un territoire auparavant administré par la wilaya de El Bayadh. Elle compte 7 communes.",
    "fact_ar": "الولاية رقم 69، أُنشئت بموجب القانون 26-06 المؤرخ في 4 أفريل 2026 من إقليم كان تابعاً لولاية البيض، وتضم 7 بلدية.",
    "fact_status": "official-reform-summary"
  }
};
